function(subdirlist result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
    foreach(child ${children})
        if(IS_DIRECTORY ${curdir}/${child})
            list(APPEND dirlist ${child} )
        endif()
    endforeach()
    set(${result} ${dirlist} PARENT_SCOPE)
endfunction(subdirlist)
