if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(BUILD_OS linux)
else()
    set(BUILD_OS win)
    if( DEFINED ENV{VcpkgIncludeDir})
        include_directories($ENV{VcpkgIncludeDir})
    endif()
    
    if(DEFINED ENV{VcpkgLibDir})
        link_directories($ENV{VcpkgLibDir})
    endif()
    if(DEFINED ENV{VcpkgDebugLibDir})
        link_directories($ENV{VcpkgDebugLibDir})
    endif()
endif()

