#source_group_by_dir()
function(source_group_by_dir)
    set(files ${ARGV0})
    foreach(filename ${files})
        SET(cur_dir ${CMAKE_CURRENT_SOURCE_DIR})
        SET(isReg 0)

        if(NOT "${ARGV1}" STREQUAL "")
            if(${filename} MATCHES "^${ARGV1}")
                SET(cur_dir ${ARGV1})
                SET(isReg 1)
            endif()
        endif()

        STRING(REGEX REPLACE "${cur_dir}" "" fpath ${filename})
        if(${isReg} EQUAL 1)
            set(fpath /${ARGV2}${fpath})
        endif()

        STRING(FIND ${fpath} "/" lastidx REVERSE)
        STRING(SUBSTRING ${fpath} 0 ${lastidx} fakegroupname)
        STRING(COMPARE EQUAL "${fakegroupname}" "" bequal)
        IF(NOT ${bequal} EQUAL 1)
            STRING(REPLACE "/" "\\" groupname ${fakegroupname})
            string(LENGTH ${groupname} igrouplength)
            set(groupname2 ${groupname})

            if(${igrouplength} GREATER 0)
                STRING(SUBSTRING ${groupname} 1 ${igrouplength}-1 groupname2)
            ELSE(${igrouplength} GREATER 0)
                SET(groupname2 "\\")
            ENDIF(${igrouplength} GREATER 0)
        ELSE(NOT ${bequal} EQUAL 1)
            SET(groupname2 "\\")
        ENDIF(NOT ${bequal} EQUAL 1)

        SOURCE_GROUP(${groupname2} FILES ${filename})
    endforeach(filename ${files})
endfunction(source_group_by_dir)